version: "3.9"
services: 
  api: 
    env_file: 
      - ./.env
    build: 
      context: ${PWD}
    volumes: 
      - .:/usr/src/app
    ports: 
      - "8000:5000"
  db: 
    image: postgres
    container_name: postgres-0
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: funky_noodle
      POSTGRES_USER: root
    ports: 
      - "5432:5432"