version: "3.9"
services: 
  api: 
    env_file: 
      - ./.env
    build: 
      context: .
    ports: 
      - "8000:5000"
  postgres: 
    image: postgres
    restart: always
    container_name: postgres-0
    user: postgres
    environment: 
      - "POSTGRES_PASSWORD=postgres"
    ports: 
      - "5432:5432"